# Generated by Django 3.1.5 on 2021-01-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj2_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poruka',
            name='content',
            field=models.CharField(max_length=128),
        ),
    ]
